# Generated by Django 5.1.2 on 2024-12-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatroom_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.TextField(default=''),
        ),
    ]
