# Generated by Django 5.1.2 on 2024-12-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_private_key_user_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key_1', models.TextField()),
                ('user_key_2', models.TextField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatroom')),
            ],
        ),
    ]
