# Generated by Django 5.1.2 on 2024-12-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatkey',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
