# Generated by Django 5.1.2 on 2024-12-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_chat_id_chatkey_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatkey',
            name='username1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatkey',
            name='username2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
