# Generated by Django 5.1.2 on 2025-02-04 07:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_groupchat_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_group_thumbnail),
        ),
    ]
